#Common configuration
server:
  port: 8050
  servlet:
    context-path: /employeemanagement

spring:
  #Configuration specific to my docker environment
  datasource:
    url: jdbc:mysql://employee-management-db:3306/assignment
    username: root
    password: pa55w0rd

  #Enabling liquibase for tracking db schema evolution
  liquibase:
    enabled: true
    change-log: /db/db-changelog.yml
  application:
    name: employee-management-backend
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true